[project]
name = "pufferlib"
version = "3.0.0"
description = "Fast and sane reinforcement learning"
requires-python = ">=3.9"
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
authors = [{ name = "Joseph Suarez", email = "jsuarez@puffer.ai" }]
classifiers = [
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = ["dependencies"]

# Default Gym/Gymnasium/PettingZoo versions
# Gym:
# - 0.26 still has deprecation warnings and is the last version of the package
# - 0.25 adds a breaking API change to reset, step, and render_modes
# - 0.24 is broken
# - 0.22-0.23 triggers deprecation warnings by calling its own functions
# - 0.21 is the most stable version
# - <= 0.20 is missing dict methods for gym.spaces.Dict
# - 0.18-0.21 require setuptools<=65.5.0
#'gym==0.23',
#'gymnasium==0.29.1',
#'pettingzoo==1.24.1',
[project.optional-dependencies]

[project.scripts]
puffer = "pufferlib.pufferl:main"

[project.urls]
Homepage = "https://puffer.ai"

[build-system]
requires = ["setuptools", "wheel", "Cython", "numpy", "torch"]
build-backend = "setuptools.build_meta"

[tool.uv]
no-build-isolation-package = ["torch"]
